import "../globals.css"
import Link from "next/link"
import Logo from "@/components/logo"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mx-auto w-full max-w-4xl font-text">
        {children}
        <footer className="py-6">
          <p className="text-xs font-bold text-neutral-500 text-center">
            Really Dope Digital LLC&copy;
          </p>
        </footer>
      </body>
    </html>
  )
}
