import { MapPinIcon, UserPlusIcon } from "@heroicons/react/24/solid"
import "../globals.css"
import Link from "next/link"
import Logo from "@/components/logo"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mx-auto w-full max-w-2xl font-text">
        <header className="">
          <div className="flex justify-center gap-16 py-12">
            <div className="pb-3">
              <Link href="/">
                <Logo className="rounded-full" />
              </Link>
            </div>

            <div className="flex flex-col justify-between">
              <div className="flex items-center justify-between gap-8">
                <div>
                  <Link href="/">thatsreallydope.com</Link>
                </div>

                <div className="flex items-center gap-1">
                  <button className="flex items-center justify-center rounded text-sm font-bold bg-neutral-500 text-white h-8 px-8">
                    Contact
                  </button>
                  <Link
                    href="https://instagram.com/reallydopestudio"
                    className="flex items-center justify-center rounded text-sm font-bold bg-neutral-500 text-white h-8 w-8 text-center"
                  >
                    <UserPlusIcon className="h-4"></UserPlusIcon>
                  </Link>
                </div>
              </div>

              <div className="">
                <h1 className="uppercase font-bold">Really Dope</h1>
                <p className="mt-3 text-sm">Creative Studio</p>
                <p className="text-sm">
                  <MapPinIcon className="-mt-1 w-3 inline-block"></MapPinIcon>{" "}
                  Los Angeles
                </p>
                <p className="mt-3 text-xs font-bold text-neutral-500">
                  Contracted by&nbsp;
                  <Link href="#" className="text-neutral-900">
                    Quillette
                  </Link>
                  ,&nbsp;
                  <Link href="#" className="text-neutral-900">
                    Etho
                  </Link>
                  ,&nbsp;
                  <Link href="#" className="text-neutral-900">
                    Flywheel
                  </Link>
                  , + 27 more
                </p>
              </div>
            </div>
          </div>

          <nav className="text-center border-t border-neutral-400">
            <Link className="inline-block p-2 mx-4" href="/">
              Projects
            </Link>
            <Link className="inline-block p-2 mx-4" href="/ideas">
              Ideas
            </Link>
            <Link className="inline-block p-4 mx-4" href="/about">
              About
            </Link>
          </nav>
        </header>
        {children}
        <footer className="mt-4 border-t border-neutral-400 py-6">
          <p className="text-xs font-bold text-neutral-500 text-center">
            Really Dope Digital LLC&copy;
          </p>
        </footer>
      </body>
    </html>
  )
}
